### ISSUE TITLE
Script causing GINA gone in 14393.321 (RS1)

### ISSUE THREAD

**Issue by iteddy123** [cluberti/VDI#7]
Script works fine for any Win10 before RS1. For RS1,
1. GINA will be gone.
2. If a user RDP into the VM, the login process will loop forever, login never get done.

It can be fixed by not touching the following service,

**Comment by weldrake13** [comment]
I also found thia however: it only happens with donain joined machines, commenting the line out of the script resolves the issue , you can reset the startup type to autonatic and it should fix itself. The login WILL happen, it just takes about 10 mins

**Comment by cluberti** [comment]
I'm not currently able to reproduce this on domain joined or non-domain joined machines (limited testing, to be fair), so I'm wondering if the RDP connection in is bringing along a Bluetooth or other non-network wireless-attached device that's triggering this?

An easy workaround is to comment this out in your environment, but I'm not 100% certain why this is happening and why only on 1607.  Hopefully I can get to the bottom of this, but for right now I'll update the script with a warning.

**Comment by weldrake13** [comment]
Hey, i found this issue while looking at optimisation in a virtualised environment (VDI deployment), the images were clean and I was able to reproduce on Xenserver and ESX as well as physical hardware but i only saw this in 1607 enterprise. I am still able to reproduce so if you want any more info to help devug I have done a lot of looking into this

**Comment by iteddy123** [comment]
Hi, same for me. Work perfect up to 1511 with latest patch. Start to fail since 1607. Yes, domain joined.
We are using Gen1 VM, hypervisor is 2012R2 and 2016, both failed.

**Comment by cluberti** [comment]
Following up on open bugs - this has been resolved.
