### ISSUE TITLE
Rename folder failed in File Explorer if enable "OneDrive" removal

### ISSUE THREAD

**Issue by iteddy123** [cluberti/VDI#8]
OS: 14393.321
If enable "Remove OneDrive", reboot, right click and create a New Folder. You can never rename this New Folder to anything else from the Explorer. It works fine with cmd.
## Problem seems caused by these two lines

```
Remove-Item -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{A52BBA46-E9E1-435f-B3D9-28DAA648C0F6}' -Recurse
Remove-Item -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{A52BBA46-E9E1-435f-B3D9-28DAA648C0F6}' -Recurse
```

---
## Also, these two lines will return, "Set-ItemProperty: Cannot find drive. A drive with name 'HKCR' does not exist"

```
Set-ItemProperty -Path 'HKCR:\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}' -Name 'System.IsPinnedToNameSpaceTree' -Value '0'
Set-ItemProperty -Path 'HKCR:\Wow6432Node\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}' -Name 'System.IsPinnedToNameSpaceTree' -Value '0' 
```

---

**Comment by jfree98** [comment]
Have there been any updates to this.?I am experiencing the same issue and cant rename folders.

**Comment by iteddy123** [comment]
Just comment out the above 4 lines in the script should fix the problem

**Comment by ssfrr** [comment]
If you've already run the script and want to recover, I found the registry script [here](http://www.winhelponline.com/blog/wp-content/uploads/q1-16/w10_folder_descriptions.zip) from [this post](http://www.winhelponline.com/blog/error-rename-move-folders-windows-10/) did the trick. When I ran it (I ran the `w10_folder_descriptions.reg` file) I got an error that not all keys were set properly, but it seems the ones I needed worked.

One could probably edit down that script substantially to just replace the OneDrive-related keys.

**Comment by cummingss** [comment]
I thought I'd provide a small update around Win10 1709 when using this script.

It would appear that the removal of these two registry keys (specifically the x64 key) also breaks windows Folder Redirection on 1709.  

Whilst the Folder Redirection Group Policy applies and there are no issues logged in event viewer, the registry values in the UserShell registry keys (which dictate the location of the redirected folders) do not change in accordance with the GPO.

I hope someone finds this helpful as I wasted a day figuring it out!

Simon.

**Comment by cluberti** [comment]
Resolved.
